#!/bin/bash
#SBATCH --job-name=checklmp       # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --mem=249G
#SBATCH --ntasks=1              # total number of tasks across all nodes. !! Change to 8 for REBO2
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --time=01:00:00          # total run time limit (HH:MM:SS)
##SBATCH --gres=gpu:1             # number of GPUs per node
##SBATCH --constraint=gpu80
#SBATCH --account=azp

module purge
module load anaconda3/2024.10
# module load cudatoolkit/12.6
module load intel-oneapi/2024.2
module load intel-mpi/oneapi/2021.13
module load intel-mkl/2024.2

conda activate jaxmd
# export XLA_PYTHON_CLIENT_PREALLOCATE=false
export XLA_PYTHON_CLIENT_MEM_FRACTION=.97
# export XLA_FLAGS="--xla_gpu_enable_command_buffer="
python test_lammps.py
